name: CI
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */5 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: microsoft/playwright-github-action@v1
      - name: Fetch
        run: npm run fetch
      - name: Commit to repo
        run: |
          git config --global user.name "spiderman"
          git config --global user.email "chenrunshan@outlook.com"
          git add pools.json && echo A
          git commit -m 'update pools' && echo B
          git push -u origin main && echo C
