name: CI
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */24 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - uses: microsoft/playwright-github-action@v1
      - name: Fetch
        run: npm install && npm run fetch
      - name: Commit to repo
        run: |
          git config --global user.name "spiderman"
          git config --global user.email "chenrunshan@outlook.com"
          git add pools.json pools-dino.json && echo _
          git commit -m 'update pools' && echo _
          git pull --rebase --autostash && echo _
          git push -u origin main && echo _
